#!/usr/bin/env python3
"""
A0 Ablation: Global XGBoost
===========================

This script reproduces the A0 ablation experiment reported in the paper:

    A0: Global XGBoost (without stacking, clustering)

Experimental design
-------------------
- Uses the development portion only; the final 20% chronological test set
  remains completely untouched.
- Uses the complete feature set produced by the preprocessing checkpoint.
- Uses the same three temporal outer validation folds used for A0.
- Trains separate XGBoost regressors for CPU and memory forecasting.
- Reports MSE, RMSE, MAE and R² for every fold.
- Reports mean ± standard deviation across the three folds.
- Saves the fold-level results and mean/SD summary as CSV files.

Expected repository structure
-----------------------------
C-CASE-GCT2019/
├── checkpoints/
│   └── ccase_step15.pkl
├── src/
│   └── ablation/
│       └── ablation_1_global_xgb.py
└── results/
    └── ablation/

Run from the repository root
----------------------------
    python src/ablation/ablation_1_global_xgb.py

Required preprocessing checkpoint
---------------------------------
The checkpoint is generated by:

    python src/preprocess_data.py

Required Python packages
------------------------
numpy
pandas
scikit-learn
xgboost
joblib

Notes
-----
The hard-coded temporal boundaries below are intentionally preserved from
the original A0 experiment so that the reported ablation remains
reproducible. They are timestamps in the same representation as the
checkpoint's ``time_bucket`` column.
"""

from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
)
from xgboost import XGBRegressor


# ============================================================================
# REPOSITORY PATHS
# ============================================================================

# This file is:
#     <repository_root>/src/ablation/ablation_1_global_xgb.py
#
# parents[0] = ablation
# parents[1] = src
# parents[2] = repository root
ROOT_DIR = Path(__file__).resolve().parents[2]

CHECKPOINT_PATH = ROOT_DIR / "checkpoints" / "ccase_step15.pkl"
OUTPUT_DIR = ROOT_DIR / "results" / "ablation"


# ============================================================================
# EXPERIMENT CONFIGURATION
# ============================================================================

RANDOM_STATE = 42

# These are the exact temporal outer-fold boundaries used in the A0
# experiment. The final chronological test set is not used here.
OUTER_FOLDS = [
    {
        "fold": "Fold1",
        "train_end": 658500000000,
        "val_start": 659100000000,
        "val_end": 1314900000000,
    },
    {
        "fold": "Fold2",
        "train_end": 1314600000000,
        "val_start": 1315200000000,
        "val_end": 1971000000000,
    },
    {
        "fold": "Fold3",
        "train_end": 1970700000000,
        "val_start": 1971300000000,
        "val_end": 2627100000000,
    },
]

# Exact XGBoost configuration used for the A0 experiment.
XGB_PARAMS = {
    "n_estimators": 150,
    "max_depth": 6,
    "learning_rate": 0.05,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "min_child_weight": 5,
    "reg_alpha": 0,
    "reg_lambda": 1,
    "tree_method": "hist",
    "n_jobs": 2,
    "random_state": RANDOM_STATE,
    "objective": "reg:squarederror",
}


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def calculate_metrics(y_true, y_pred):
    """Calculate the regression metrics reported for the ablation study."""
    mse = mean_squared_error(y_true, y_pred)

    return {
        "MSE": mse,
        "RMSE": np.sqrt(mse),
        "MAE": mean_absolute_error(y_true, y_pred),
        "R2": r2_score(y_true, y_pred),
    }


def validate_temporal_fold(train_data, fold_config):
    """
    Validate that the requested training and validation periods are
    temporally separated and non-empty.
    """
    time_values = train_data["time_bucket"]

    train_mask = time_values <= fold_config["train_end"]
    val_mask = (
        (time_values >= fold_config["val_start"])
        & (time_values <= fold_config["val_end"])
    )

    if not train_mask.any():
        raise RuntimeError(
            f"{fold_config['fold']} contains no training observations."
        )

    if not val_mask.any():
        raise RuntimeError(
            f"{fold_config['fold']} contains no validation observations."
        )

    train_max_time = time_values.loc[train_mask].max()
    val_min_time = time_values.loc[val_mask].min()

    if train_max_time >= val_min_time:
        raise RuntimeError(
            f"Temporal leakage detected in {fold_config['fold']}: "
            f"training maximum time ({train_max_time}) is not earlier than "
            f"validation minimum time ({val_min_time})."
        )

    return train_mask, val_mask


# ============================================================================
# MAIN EXPERIMENT
# ============================================================================

def main():
    print("=" * 80)
    print("A0 ABLATION — GLOBAL XGBOOST")
    print("Without Stacking and Without Clustering")
    print("=" * 80)

    # ------------------------------------------------------------------------
    # STEP 1 — CHECK REQUIRED CHECKPOINT
    # ------------------------------------------------------------------------
    if not CHECKPOINT_PATH.exists():
        raise FileNotFoundError(
            "\nRequired preprocessing checkpoint was not found.\n\n"
            f"Expected location:\n{CHECKPOINT_PATH}\n\n"
            "Please run the preprocessing step first:\n\n"
            "    python src/preprocess_data.py\n\n"
            "The preprocessing script should generate:\n"
            "    checkpoints/ccase_step15.pkl\n"
        )

    # ------------------------------------------------------------------------
    # STEP 2 — LOAD CHECKPOINT
    # ------------------------------------------------------------------------
    print("\n" + "=" * 80)
    print("STEP 1 — LOAD PREPROCESSING CHECKPOINT")
    print("=" * 80)
    print(f"Checkpoint: {CHECKPOINT_PATH}")

    checkpoint = joblib.load(CHECKPOINT_PATH)

    required_keys = [
        "model_data",
        "feature_cols",
        "train_data",
    ]

    missing_keys = [
        key for key in required_keys
        if key not in checkpoint
    ]

    if missing_keys:
        raise KeyError(
            "The preprocessing checkpoint is missing required keys: "
            + ", ".join(missing_keys)
        )

    model_data = checkpoint["model_data"]
    feature_cols = checkpoint["feature_cols"]
    train_data = checkpoint["train_data"].copy()

    required_columns = (
        list(feature_cols)
        + [
            "future_cpu",
            "future_memory",
            "time_bucket",
        ]
    )

    missing_columns = [
        col for col in required_columns
        if col not in train_data.columns
    ]

    if missing_columns:
        raise KeyError(
            "The checkpoint's train_data is missing required columns: "
            + ", ".join(missing_columns)
        )

    print("Checkpoint loaded successfully.")
    print("Model-data shape:", getattr(model_data, "shape", "not available"))
    print("Development data shape:", train_data.shape)
    print("Number of features:", len(feature_cols))

    # ------------------------------------------------------------------------
    # STEP 3 — PREPARE DEVELOPMENT DATA
    # ------------------------------------------------------------------------
    #
    # A0 is deliberately a GLOBAL XGBoost baseline:
    # - no clustering is used;
    # - no cluster/context variables are added;
    # - no stacking/meta learner is used.
    #
    # The final 20% chronological test set is already excluded from
    # checkpoint["train_data"] by the preprocessing pipeline.
    # ------------------------------------------------------------------------
    print("\n" + "=" * 80)
    print("STEP 2 — PREPARE DEVELOPMENT DATA")
    print("=" * 80)

    X_all = train_data[feature_cols]
    y_cpu_all = train_data["future_cpu"]
    y_memory_all = train_data["future_memory"]
    time_all = train_data["time_bucket"]

    if X_all.isnull().any().any():
        raise ValueError(
            "Feature matrix contains missing values. "
            "Please check preprocessing before running A0."
        )

    if y_cpu_all.isnull().any():
        raise ValueError(
            "CPU target contains missing values. "
            "Please check preprocessing before running A0."
        )

    if y_memory_all.isnull().any():
        raise ValueError(
            "Memory target contains missing values. "
            "Please check preprocessing before running A0."
        )

    if time_all.isnull().any():
        raise ValueError(
            "time_bucket contains missing values. "
            "Please check preprocessing before running A0."
        )

    print("Development observations:", len(train_data))
    print("Feature matrix shape:", X_all.shape)

    # ------------------------------------------------------------------------
    # STEP 4 — RUN TEMPORAL OUTER FOLDS
    # ------------------------------------------------------------------------
    print("\n" + "=" * 80)
    print("STEP 3 — TEMPORAL OUTER-FOLD EVALUATION")
    print("=" * 80)

    fold_results = []
    fold_predictions = []

    for fold_config in OUTER_FOLDS:
        fold_name = fold_config["fold"]

        print("\n" + "-" * 80)
        print(f"{fold_name}")
        print("-" * 80)

        train_mask, val_mask = validate_temporal_fold(
            train_data,
            fold_config,
        )

        X_train = X_all.loc[train_mask]
        X_val = X_all.loc[val_mask]

        y_cpu_train = y_cpu_all.loc[train_mask]
        y_cpu_val = y_cpu_all.loc[val_mask]

        y_memory_train = y_memory_all.loc[train_mask]
        y_memory_val = y_memory_all.loc[val_mask]

        time_train = time_all.loc[train_mask]
        time_val = time_all.loc[val_mask]

        print("Training observations :", len(X_train))
        print("Validation observations:", len(X_val))
        print("Training max time     :", time_train.max())
        print("Validation min time   :", time_val.min())

        # --------------------------------------------------------------------
        # CPU XGBoost
        # --------------------------------------------------------------------
        print("\nTraining CPU XGBoost...")

        cpu_model = XGBRegressor(**XGB_PARAMS)
        cpu_model.fit(X_train, y_cpu_train)

        cpu_pred = cpu_model.predict(X_val)
        cpu_metrics = calculate_metrics(
            y_cpu_val,
            cpu_pred,
        )

        # --------------------------------------------------------------------
        # MEMORY XGBoost
        # --------------------------------------------------------------------
        print("Training Memory XGBoost...")

        memory_model = XGBRegressor(**XGB_PARAMS)
        memory_model.fit(X_train, y_memory_train)

        memory_pred = memory_model.predict(X_val)
        memory_metrics = calculate_metrics(
            y_memory_val,
            memory_pred,
        )

        # --------------------------------------------------------------------
        # STORE FOLD RESULTS
        # --------------------------------------------------------------------
        fold_results.append(
            {
                "Fold": fold_name,
                "CPU_MSE": cpu_metrics["MSE"],
                "CPU_RMSE": cpu_metrics["RMSE"],
                "CPU_MAE": cpu_metrics["MAE"],
                "CPU_R2": cpu_metrics["R2"],
                "Memory_MSE": memory_metrics["MSE"],
                "Memory_RMSE": memory_metrics["RMSE"],
                "Memory_MAE": memory_metrics["MAE"],
                "Memory_R2": memory_metrics["R2"],
                "Train_Size": len(X_train),
                "Validation_Size": len(X_val),
                "Train_Max_Time": time_train.max(),
                "Validation_Min_Time": time_val.min(),
            }
        )

        # Keep fold predictions available for reproducibility/output.
        fold_predictions.append(
            {
                "Fold": fold_name,
                "time": time_val.to_numpy(),
                "y_cpu": y_cpu_val.to_numpy(),
                "pred_cpu": cpu_pred,
                "y_memory": y_memory_val.to_numpy(),
                "pred_memory": memory_pred,
            }
        )

        print("\nCPU metrics:")
        print(f"  MSE  : {cpu_metrics['MSE']:.10e}")
        print(f"  RMSE : {cpu_metrics['RMSE']:.10e}")
        print(f"  MAE  : {cpu_metrics['MAE']:.10e}")
        print(f"  R²   : {cpu_metrics['R2']:.10f}")

        print("\nMemory metrics:")
        print(f"  MSE  : {memory_metrics['MSE']:.10e}")
        print(f"  RMSE : {memory_metrics['RMSE']:.10e}")
        print(f"  MAE  : {memory_metrics['MAE']:.10e}")
        print(f"  R²   : {memory_metrics['R2']:.10f}")

    # ------------------------------------------------------------------------
    # STEP 5 — CREATE RESULTS DATAFRAME
    # ------------------------------------------------------------------------
    a0_results = pd.DataFrame(fold_results)

    # ------------------------------------------------------------------------
    # STEP 6 — MEAN ± SD ACROSS OUTER FOLDS
    # ------------------------------------------------------------------------
    #
    # ddof=1 gives the sample standard deviation, which is appropriate for
    # reporting variability across the three outer validation folds.
    # ------------------------------------------------------------------------
    metric_columns = [
        "CPU_MSE",
        "CPU_RMSE",
        "CPU_MAE",
        "CPU_R2",
        "Memory_MSE",
        "Memory_RMSE",
        "Memory_MAE",
        "Memory_R2",
    ]

    summary_rows = []

    for metric in metric_columns:
        summary_rows.append(
            {
                "Metric": metric,
                "Mean": a0_results[metric].mean(),
                "SD": a0_results[metric].std(ddof=1),
            }
        )

    summary = pd.DataFrame(summary_rows)

    # ------------------------------------------------------------------------
    # STEP 7 — SAVE RESULTS
    # ------------------------------------------------------------------------
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    fold_results_path = (
        OUTPUT_DIR / "A0_Global_XGBoost_outer_fold_results.csv"
    )

    summary_path = (
        OUTPUT_DIR / "A0_Global_XGBoost_mean_sd.csv"
    )

    predictions_path = (
        OUTPUT_DIR / "A0_Global_XGBoost_predictions.npz"
    )

    a0_results.to_csv(
        fold_results_path,
        index=False,
    )

    summary.to_csv(
        summary_path,
        index=False,
    )

    # Save fold predictions in a single compressed NPZ file.
    # Object arrays are used because validation-fold lengths may differ.
    np.savez_compressed(
        predictions_path,
        fold_names=np.array(
            [item["Fold"] for item in fold_predictions],
            dtype=object,
        ),
        times=np.array(
            [item["time"] for item in fold_predictions],
            dtype=object,
        ),
        y_cpu=np.array(
            [item["y_cpu"] for item in fold_predictions],
            dtype=object,
        ),
        pred_cpu=np.array(
            [item["pred_cpu"] for item in fold_predictions],
            dtype=object,
        ),
        y_memory=np.array(
            [item["y_memory"] for item in fold_predictions],
            dtype=object,
        ),
        pred_memory=np.array(
            [item["pred_memory"] for item in fold_predictions],
            dtype=object,
        ),
    )

    # ------------------------------------------------------------------------
    # STEP 8 — PRINT FINAL RESULTS
    # ------------------------------------------------------------------------
    print("\n" + "=" * 80)
    print("A0 GLOBAL XGBOOST — OUTER-FOLD RESULTS")
    print("=" * 80)
    print(a0_results.to_string(index=False))

    print("\n" + "=" * 80)
    print("A0 GLOBAL XGBOOST — MEAN ± SD")
    print("=" * 80)
    print(summary.to_string(index=False))

    print("\n" + "=" * 80)
    print("FILES SAVED")
    print("=" * 80)
    print(f"Fold results : {fold_results_path}")
    print(f"Mean ± SD    : {summary_path}")
    print(f"Predictions  : {predictions_path}")

    print("\nA0 Global XGBoost completed successfully.")


if __name__ == "__main__":
    main()
