#!/usr/bin/env python3
"""
Robustness Experiment for the C-CASE Green Cloud Workload Forecasting Study.

Purpose
-------
Repeat the complete model-comparison experiment for five independent model
random seeds and report mean +/- sample standard deviation (SD) across runs.

Models evaluated:
    1. Linear Regression
    2. Random Forest
    3. XGBoost
    4. Stacked Ensemble (No Clustering)
    5. Proposed C-CASE

Experimental protocol preserved from the supplied robustness notebook:
    - Google Cluster Trace 2019 checkpoint as the data source.
    - Chronological 80:20 development/test split already represented by the
      checkpoint.
    - StandardScaler fitted on the 80% development data only.
    - K-Means with K=6, n_init=10, random_state=42.
    - Test rows are assigned to the fitted development K-Means model.
    - Three-fold TimeSeriesSplit for leakage-free temporal OOF predictions.
    - LR + RF + XGB base learners.
    - XGB meta learner for both no-clustering stacking and C-CASE.
    - C-CASE meta features = three base predictions + six one-hot cluster
      context variables.
    - Untouched 20% test set is used only for final evaluation.
    - Robustness seeds = [42, 123, 2024, 3407, 7777].

The script is repository-relative and intended to run from the repository root:

    python src/robustness.py

Expected repository layout:
    C-CASE-GCT2019/
    ├── checkpoints/
    │   └── ccase_step15.pkl
    ├── src/
    │   └── robustness.py
    └── results/
        └── robustness/

The checkpoint must be generated by the repository preprocessing pipeline.
"""

from __future__ import annotations

import gc
from pathlib import Path
from typing import Dict, Tuple

import joblib
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
)
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import StandardScaler
from xgboost import XGBRegressor


# ---------------------------------------------------------------------------
# Repository paths
# ---------------------------------------------------------------------------

ROOT_DIR = Path(__file__).resolve().parents[1]
CHECKPOINT_PATH = ROOT_DIR / "checkpoints" / "ccase_step15.pkl"
OUTPUT_DIR = ROOT_DIR / "results" / "robustness"

# ---------------------------------------------------------------------------
# Experiment configuration
# ---------------------------------------------------------------------------

TARGET_CPU = "future_cpu"
TARGET_MEMORY = "future_memory"

N_SPLITS = 3
N_CLUSTERS = 6
EXPECTED_TEST_SIZE = 283_864

ROBUSTNESS_SEEDS = [42, 123, 2024, 3407, 7777]

# K-Means is deliberately fixed to the protocol in the supplied notebook.
KMEANS_SEED = 42
KMEANS_N_INIT = 10

RF_BASE_PARAMS = {
    "n_estimators": 150,
    "max_depth": 12,
    "min_samples_leaf": 2,
    "max_features": "sqrt",
    "n_jobs": 2,
}

XGB_BASE_PARAMS = {
    "n_estimators": 150,
    "max_depth": 6,
    "learning_rate": 0.05,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "min_child_weight": 5,
    "reg_alpha": 0,
    "reg_lambda": 1,
    "tree_method": "hist",
    "n_jobs": 2,
    "objective": "reg:squarederror",
}

META_XGB_PARAMS = {
    "n_estimators": 150,
    "max_depth": 4,
    "learning_rate": 0.05,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "min_child_weight": 5,
    "reg_alpha": 0,
    "reg_lambda": 1,
    "tree_method": "hist",
    "n_jobs": 2,
    "objective": "reg:squarederror",
}


# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

def calculate_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
) -> Tuple[float, float, float, float]:
    """Return MSE, RMSE, MAE and R2."""
    mse = mean_squared_error(y_true, y_pred)
    rmse = float(np.sqrt(mse))
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    return float(mse), rmse, float(mae), float(r2)


def validate_finite(name: str, array: np.ndarray) -> None:
    """Fail early if an array contains NaN or infinite values."""
    if not np.isfinite(array).all():
        raise ValueError(f"{name} contains NaN or infinite values.")


def load_checkpoint() -> tuple[dict, pd.DataFrame, pd.DataFrame, list[str]]:
    """Load and validate the preprocessing checkpoint."""
    if not CHECKPOINT_PATH.exists():
        raise FileNotFoundError(
            f"Checkpoint not found:\n  {CHECKPOINT_PATH}\n\n"
            "Generate it first using the repository preprocessing pipeline."
        )

    checkpoint = joblib.load(CHECKPOINT_PATH)

    required_keys = {"train_data", "test_data", "feature_cols"}
    missing = required_keys.difference(checkpoint.keys())
    if missing:
        raise KeyError(
            "Checkpoint is missing required keys: "
            + ", ".join(sorted(missing))
        )

    train_data = checkpoint["train_data"].copy()
    test_data = checkpoint["test_data"].copy()
    feature_cols = list(checkpoint["feature_cols"])

    required_columns = set(feature_cols) | {
        TARGET_CPU,
        TARGET_MEMORY,
    }

    for frame_name, frame in (
        ("train_data", train_data),
        ("test_data", test_data),
    ):
        missing_columns = required_columns.difference(frame.columns)
        if missing_columns:
            raise KeyError(
                f"{frame_name} is missing required columns: "
                + ", ".join(sorted(missing_columns))
            )

    if len(test_data) != EXPECTED_TEST_SIZE:
        raise ValueError(
            f"Expected {EXPECTED_TEST_SIZE:,} test rows, "
            f"but checkpoint contains {len(test_data):,}."
        )

    if train_data[feature_cols].isna().any().any():
        raise ValueError("Development features contain missing values.")

    if test_data[feature_cols].isna().any().any():
        raise ValueError("Test features contain missing values.")

    if train_data[[TARGET_CPU, TARGET_MEMORY]].isna().any().any():
        raise ValueError("Development targets contain missing values.")

    if test_data[[TARGET_CPU, TARGET_MEMORY]].isna().any().any():
        raise ValueError("Test targets contain missing values.")

    return checkpoint, train_data, test_data, feature_cols


def prepare_data(
    train_data: pd.DataFrame,
    test_data: pd.DataFrame,
    feature_cols: list[str],
) -> dict:
    """
    Fit preprocessing on development data only.

    This reproduces the supplied notebook's robustness preprocessing:
    StandardScaler -> KMeans(K=6) -> one-hot cluster context.
    """
    X_dev = train_data[feature_cols].to_numpy(dtype=np.float64)
    X_test = test_data[feature_cols].to_numpy(dtype=np.float64)

    y_dev_cpu = train_data[TARGET_CPU].to_numpy(dtype=np.float64)
    y_dev_mem = train_data[TARGET_MEMORY].to_numpy(dtype=np.float64)
    y_test_cpu = test_data[TARGET_CPU].to_numpy(dtype=np.float64)
    y_test_mem = test_data[TARGET_MEMORY].to_numpy(dtype=np.float64)

    scaler = StandardScaler()
    X_dev_scaled = scaler.fit_transform(X_dev)
    X_test_scaled = scaler.transform(X_test)

    kmeans = KMeans(
        n_clusters=N_CLUSTERS,
        random_state=KMEANS_SEED,
        n_init=KMEANS_N_INIT,
    )

    cluster_dev = kmeans.fit_predict(X_dev_scaled)
    cluster_test = kmeans.predict(X_test_scaled)

    cluster_dev_oh = np.eye(N_CLUSTERS, dtype=np.float64)[cluster_dev]
    cluster_test_oh = np.eye(N_CLUSTERS, dtype=np.float64)[cluster_test]

    validate_finite("X_dev_scaled", X_dev_scaled)
    validate_finite("X_test_scaled", X_test_scaled)
    validate_finite("y_dev_cpu", y_dev_cpu)
    validate_finite("y_dev_mem", y_dev_mem)
    validate_finite("y_test_cpu", y_test_cpu)
    validate_finite("y_test_mem", y_test_mem)

    if X_dev_scaled.shape[1] != len(feature_cols):
        raise ValueError("Scaled feature count does not match feature_cols.")

    if cluster_dev_oh.shape != (len(train_data), N_CLUSTERS):
        raise ValueError("Development cluster-context shape is incorrect.")

    if cluster_test_oh.shape != (len(test_data), N_CLUSTERS):
        raise ValueError("Test cluster-context shape is incorrect.")

    return {
        "X_dev_scaled": X_dev_scaled,
        "X_test_scaled": X_test_scaled,
        "y_dev_cpu": y_dev_cpu,
        "y_dev_mem": y_dev_mem,
        "y_test_cpu": y_test_cpu,
        "y_test_mem": y_test_mem,
        "cluster_dev": cluster_dev,
        "cluster_test": cluster_test,
        "cluster_dev_oh": cluster_dev_oh,
        "cluster_test_oh": cluster_test_oh,
        "scaler": scaler,
        "kmeans": kmeans,
    }


def create_rf(seed: int) -> RandomForestRegressor:
    """Create a base Random Forest with the prescribed seed."""
    return RandomForestRegressor(
        **RF_BASE_PARAMS,
        random_state=seed,
    )


def create_xgb(seed: int) -> XGBRegressor:
    """Create a base XGBoost model with the prescribed seed."""
    return XGBRegressor(
        **XGB_BASE_PARAMS,
        random_state=seed,
    )


def create_meta_xgb(seed: int) -> XGBRegressor:
    """Create an XGBoost meta learner with the prescribed seed."""
    return XGBRegressor(
        **META_XGB_PARAMS,
        random_state=seed,
    )


def generate_temporal_oof(
    X_dev_scaled: np.ndarray,
    y_dev_cpu: np.ndarray,
    y_dev_mem: np.ndarray,
    seed: int,
) -> Dict[str, np.ndarray]:
    """
    Generate leakage-free three-fold temporal OOF predictions.

    TimeSeriesSplit always trains on observations earlier than its validation
    block. The initial observations without OOF predictions are excluded from
    meta-training, exactly as in the supplied notebook.
    """
    n_dev = len(X_dev_scaled)

    oof = {
        "cpu_lr": np.full(n_dev, np.nan, dtype=np.float64),
        "cpu_rf": np.full(n_dev, np.nan, dtype=np.float64),
        "cpu_xgb": np.full(n_dev, np.nan, dtype=np.float64),
        "mem_lr": np.full(n_dev, np.nan, dtype=np.float64),
        "mem_rf": np.full(n_dev, np.nan, dtype=np.float64),
        "mem_xgb": np.full(n_dev, np.nan, dtype=np.float64),
    }

    tscv = TimeSeriesSplit(n_splits=N_SPLITS)

    for fold, (train_idx, val_idx) in enumerate(
        tscv.split(X_dev_scaled), start=1
    ):
        if train_idx.max() >= val_idx.min():
            raise RuntimeError(
                f"Temporal leakage detected in OOF fold {fold}."
            )

        X_train = X_dev_scaled[train_idx]
        X_val = X_dev_scaled[val_idx]

        # CPU base models
        cpu_lr = LinearRegression()
        cpu_rf = create_rf(seed)
        cpu_xgb = create_xgb(seed)

        cpu_lr.fit(X_train, y_dev_cpu[train_idx])
        cpu_rf.fit(X_train, y_dev_cpu[train_idx])
        cpu_xgb.fit(X_train, y_dev_cpu[train_idx])

        oof["cpu_lr"][val_idx] = cpu_lr.predict(X_val)
        oof["cpu_rf"][val_idx] = cpu_rf.predict(X_val)
        oof["cpu_xgb"][val_idx] = cpu_xgb.predict(X_val)

        # Memory base models
        mem_lr = LinearRegression()
        mem_rf = create_rf(seed)
        mem_xgb = create_xgb(seed)

        mem_lr.fit(X_train, y_dev_mem[train_idx])
        mem_rf.fit(X_train, y_dev_mem[train_idx])
        mem_xgb.fit(X_train, y_dev_mem[train_idx])

        oof["mem_lr"][val_idx] = mem_lr.predict(X_val)
        oof["mem_rf"][val_idx] = mem_rf.predict(X_val)
        oof["mem_xgb"][val_idx] = mem_xgb.predict(X_val)

        print(
            f"    OOF fold {fold}: "
            f"train={len(train_idx):,}, validation={len(val_idx):,}"
        )

        del (
            cpu_lr,
            cpu_rf,
            cpu_xgb,
            mem_lr,
            mem_rf,
            mem_xgb,
            X_train,
            X_val,
        )
        gc.collect()

    oof_mask = np.ones(n_dev, dtype=bool)
    for values in oof.values():
        oof_mask &= np.isfinite(values)

    valid_rows = int(oof_mask.sum())
    if valid_rows == 0:
        raise RuntimeError("No complete OOF rows were generated.")

    if valid_rows >= n_dev:
        raise RuntimeError(
            "Expected initial TimeSeriesSplit rows without OOF predictions."
        )

    for name, values in oof.items():
        validate_finite(
            f"OOF {name} on valid rows",
            values[oof_mask],
        )

    oof["mask"] = oof_mask
    return oof


def fit_final_base_models(
    X_dev_scaled: np.ndarray,
    y_dev_cpu: np.ndarray,
    y_dev_mem: np.ndarray,
    seed: int,
) -> Dict[str, object]:
    """Fit all six base models on the complete development set."""
    models = {
        "cpu_lr": LinearRegression(),
        "cpu_rf": create_rf(seed),
        "cpu_xgb": create_xgb(seed),
        "mem_lr": LinearRegression(),
        "mem_rf": create_rf(seed),
        "mem_xgb": create_xgb(seed),
    }

    models["cpu_lr"].fit(X_dev_scaled, y_dev_cpu)
    models["cpu_rf"].fit(X_dev_scaled, y_dev_cpu)
    models["cpu_xgb"].fit(X_dev_scaled, y_dev_cpu)

    models["mem_lr"].fit(X_dev_scaled, y_dev_mem)
    models["mem_rf"].fit(X_dev_scaled, y_dev_mem)
    models["mem_xgb"].fit(X_dev_scaled, y_dev_mem)

    return models


def run_one_seed(
    seed: int,
    data: dict,
) -> tuple[pd.DataFrame, dict[str, np.ndarray]]:
    """Run the complete robustness experiment for one random seed."""
    X_dev_scaled = data["X_dev_scaled"]
    X_test_scaled = data["X_test_scaled"]
    y_dev_cpu = data["y_dev_cpu"]
    y_dev_mem = data["y_dev_mem"]
    y_test_cpu = data["y_test_cpu"]
    y_test_mem = data["y_test_mem"]
    cluster_dev_oh = data["cluster_dev_oh"]
    cluster_test_oh = data["cluster_test_oh"]

    print("\n" + "=" * 78)
    print(f"ROBUSTNESS RUN — SEED {seed}")
    print("=" * 78)

    # 1. Temporal OOF base predictions
    print("\n[1/5] Generating leakage-free temporal OOF predictions...")
    oof = generate_temporal_oof(
        X_dev_scaled,
        y_dev_cpu,
        y_dev_mem,
        seed,
    )
    oof_mask = oof["mask"]

    # 2. Meta-training features
    print("\n[2/5] Creating meta-training datasets...")

    meta_cpu_base = np.column_stack([
        oof["cpu_lr"][oof_mask],
        oof["cpu_rf"][oof_mask],
        oof["cpu_xgb"][oof_mask],
    ])

    meta_mem_base = np.column_stack([
        oof["mem_lr"][oof_mask],
        oof["mem_rf"][oof_mask],
        oof["mem_xgb"][oof_mask],
    ])

    meta_cluster = cluster_dev_oh[oof_mask]

    meta_cpu_no_cluster = meta_cpu_base
    meta_mem_no_cluster = meta_mem_base

    meta_cpu_ccase = np.column_stack([
        meta_cpu_base,
        meta_cluster,
    ])

    meta_mem_ccase = np.column_stack([
        meta_mem_base,
        meta_cluster,
    ])

    meta_y_cpu = y_dev_cpu[oof_mask]
    meta_y_mem = y_dev_mem[oof_mask]

    if meta_cpu_no_cluster.shape[1] != 3:
        raise RuntimeError("No-clustering CPU meta features must have 3 columns.")
    if meta_mem_no_cluster.shape[1] != 3:
        raise RuntimeError("No-clustering memory meta features must have 3 columns.")
    if meta_cpu_ccase.shape[1] != 9:
        raise RuntimeError("C-CASE CPU meta features must have 9 columns.")
    if meta_mem_ccase.shape[1] != 9:
        raise RuntimeError("C-CASE memory meta features must have 9 columns.")

    # 3. Train meta learners
    print("\n[3/5] Training XGBoost meta learners...")

    meta_cpu_no_cluster_model = create_meta_xgb(seed)
    meta_mem_no_cluster_model = create_meta_xgb(seed)
    meta_cpu_ccase_model = create_meta_xgb(seed)
    meta_mem_ccase_model = create_meta_xgb(seed)

    meta_cpu_no_cluster_model.fit(
        meta_cpu_no_cluster,
        meta_y_cpu,
    )
    meta_mem_no_cluster_model.fit(
        meta_mem_no_cluster,
        meta_y_mem,
    )
    meta_cpu_ccase_model.fit(
        meta_cpu_ccase,
        meta_y_cpu,
    )
    meta_mem_ccase_model.fit(
        meta_mem_ccase,
        meta_y_mem,
    )

    # 4. Refit base learners on all development data
    print("\n[4/5] Training final base models on all development rows...")

    base_models = fit_final_base_models(
        X_dev_scaled,
        y_dev_cpu,
        y_dev_mem,
        seed,
    )

    # 5. Predict untouched test data
    print("\n[5/5] Predicting on untouched test data...")

    test_cpu_lr = base_models["cpu_lr"].predict(X_test_scaled)
    test_cpu_rf = base_models["cpu_rf"].predict(X_test_scaled)
    test_cpu_xgb = base_models["cpu_xgb"].predict(X_test_scaled)

    test_mem_lr = base_models["mem_lr"].predict(X_test_scaled)
    test_mem_rf = base_models["mem_rf"].predict(X_test_scaled)
    test_mem_xgb = base_models["mem_xgb"].predict(X_test_scaled)

    test_cpu_no_cluster = np.column_stack([
        test_cpu_lr,
        test_cpu_rf,
        test_cpu_xgb,
    ])
    test_mem_no_cluster = np.column_stack([
        test_mem_lr,
        test_mem_rf,
        test_mem_xgb,
    ])

    test_cpu_ccase = np.column_stack([
        test_cpu_lr,
        test_cpu_rf,
        test_cpu_xgb,
        cluster_test_oh,
    ])
    test_mem_ccase = np.column_stack([
        test_mem_lr,
        test_mem_rf,
        test_mem_xgb,
        cluster_test_oh,
    ])

    test_cpu_stacked = meta_cpu_no_cluster_model.predict(
        test_cpu_no_cluster
    )
    test_mem_stacked = meta_mem_no_cluster_model.predict(
        test_mem_no_cluster
    )

    test_cpu_ccase_pred = meta_cpu_ccase_model.predict(
        test_cpu_ccase
    )
    test_mem_ccase_pred = meta_mem_ccase_model.predict(
        test_mem_ccase
    )

    prediction_map = {
        "Linear Regression": (test_cpu_lr, test_mem_lr),
        "Random Forest": (test_cpu_rf, test_mem_rf),
        "XGBoost": (test_cpu_xgb, test_mem_xgb),
        "Stacked Ensemble (No Clustering)": (
            test_cpu_stacked,
            test_mem_stacked,
        ),
        "Proposed C-CASE": (
            test_cpu_ccase_pred,
            test_mem_ccase_pred,
        ),
    }

    run_results = []

    for model_name, (cpu_pred, mem_pred) in prediction_map.items():
        validate_finite(f"{model_name} CPU predictions", cpu_pred)
        validate_finite(f"{model_name} memory predictions", mem_pred)

        cpu_mse, cpu_rmse, cpu_mae, cpu_r2 = calculate_metrics(
            y_test_cpu,
            cpu_pred,
        )
        mem_mse, mem_rmse, mem_mae, mem_r2 = calculate_metrics(
            y_test_mem,
            mem_pred,
        )

        run_results.append({
            "Seed": seed,
            "Model": model_name,
            "CPU MSE": cpu_mse,
            "CPU RMSE": cpu_rmse,
            "CPU MAE": cpu_mae,
            "CPU R2": cpu_r2,
            "Memory MSE": mem_mse,
            "Memory RMSE": mem_rmse,
            "Memory MAE": mem_mae,
            "Memory R2": mem_r2,
            "OOF Rows": int(oof_mask.sum()),
        })

    predictions = {
        f"seed_{seed}_y_cpu": y_test_cpu.copy(),
        f"seed_{seed}_y_memory": y_test_mem.copy(),
        f"seed_{seed}_LR_cpu": test_cpu_lr.copy(),
        f"seed_{seed}_LR_memory": test_mem_lr.copy(),
        f"seed_{seed}_RF_cpu": test_cpu_rf.copy(),
        f"seed_{seed}_RF_memory": test_mem_rf.copy(),
        f"seed_{seed}_XGB_cpu": test_cpu_xgb.copy(),
        f"seed_{seed}_XGB_memory": test_mem_xgb.copy(),
        f"seed_{seed}_Stacked_cpu": test_cpu_stacked.copy(),
        f"seed_{seed}_Stacked_memory": test_mem_stacked.copy(),
        f"seed_{seed}_CCASE_cpu": test_cpu_ccase_pred.copy(),
        f"seed_{seed}_CCASE_memory": test_mem_ccase_pred.copy(),
        f"seed_{seed}_cluster": data["cluster_test"].copy(),
    }

    # Explicit common-test-size checks
    for name, values in predictions.items():
        if len(values) != EXPECTED_TEST_SIZE:
            raise RuntimeError(
                f"{name} has {len(values):,} rows; expected "
                f"{EXPECTED_TEST_SIZE:,}."
            )

    run_df = pd.DataFrame(run_results)

    print("\nRun results:")
    print(
        run_df[
            ["Model", "CPU R2", "Memory R2"]
        ].to_string(
            index=False,
            float_format=lambda value: f"{value:.6f}",
        )
    )

    # Release model objects before the next seed.
    del (
        oof,
        meta_cpu_no_cluster_model,
        meta_mem_no_cluster_model,
        meta_cpu_ccase_model,
        meta_mem_ccase_model,
        base_models,
    )
    gc.collect()

    return run_df, predictions


def create_mean_sd_table(results: pd.DataFrame) -> pd.DataFrame:
    """
    Aggregate the five runs using arithmetic mean and sample SD (ddof=1).
    """
    metric_columns = [
        "CPU MSE",
        "CPU RMSE",
        "CPU MAE",
        "CPU R2",
        "Memory MSE",
        "Memory RMSE",
        "Memory MAE",
        "Memory R2",
    ]

    mean_table = (
        results.groupby("Model", sort=False)[metric_columns]
        .mean()
        .reset_index()
    )

    sd_table = (
        results.groupby("Model", sort=False)[metric_columns]
        .std(ddof=1)
        .reset_index()
    )

    output = mean_table.copy()

    for metric in metric_columns:
        output[f"{metric} Mean"] = mean_table[metric]
        output[f"{metric} SD"] = sd_table[metric]

    output = output[
        ["Model"]
        + [
            column
            for metric in metric_columns
            for column in (
                f"{metric} Mean",
                f"{metric} SD",
            )
        ]
    ]

    return output


def save_outputs(
    results: pd.DataFrame,
    mean_sd: pd.DataFrame,
    predictions: dict[str, np.ndarray],
    data: dict,
) -> None:
    """Save reviewer-friendly robustness outputs."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    results_path = OUTPUT_DIR / "robustness_all_runs.csv"
    mean_sd_path = OUTPUT_DIR / "robustness_mean_sd.csv"
    predictions_path = OUTPUT_DIR / "robustness_test_predictions.npz"
    preprocessing_path = OUTPUT_DIR / "robustness_preprocessing.pkl"
    config_path = OUTPUT_DIR / "robustness_config.txt"

    results.to_csv(results_path, index=False)
    mean_sd.to_csv(mean_sd_path, index=False)

    np.savez_compressed(
        predictions_path,
        **predictions,
    )

    # Save fitted preprocessing objects and cluster assignments so that the
    # exact robustness cluster context can be inspected independently.
    joblib.dump(
        {
            "scaler": data["scaler"],
            "kmeans": data["kmeans"],
            "cluster_dev": data["cluster_dev"],
            "cluster_test": data["cluster_test"],
            "feature_cols": FEATURE_COLS_FOR_OUTPUT,
            "n_clusters": N_CLUSTERS,
            "kmeans_random_state": KMEANS_SEED,
            "kmeans_n_init": KMEANS_N_INIT,
        },
        preprocessing_path,
    )

    config_path.write_text(
        "\n".join([
            "C-CASE Robustness Experiment",
            "==============================",
            f"Seeds: {ROBUSTNESS_SEEDS}",
            f"Temporal OOF splits: {N_SPLITS}",
            f"K-Means clusters: {N_CLUSTERS}",
            f"K-Means random_state: {KMEANS_SEED}",
            f"K-Means n_init: {KMEANS_N_INIT}",
            f"Expected test rows: {EXPECTED_TEST_SIZE}",
            "Scaler: StandardScaler fitted on development data only",
            "Base RF: 150 trees, max_depth=12, min_samples_leaf=2, max_features=sqrt",
            "Base XGB: 150 trees, max_depth=6, learning_rate=0.05, "
            "subsample=0.8, colsample_bytree=0.8, min_child_weight=5",
            "Meta XGB: 150 trees, max_depth=4, learning_rate=0.05, "
            "subsample=0.8, colsample_bytree=0.8, min_child_weight=5",
            "Evaluation: untouched chronological 20% test set",
            "SD: sample standard deviation (ddof=1)",
        ]),
        encoding="utf-8",
    )

    print("\nSaved outputs:")
    for path in (
        results_path,
        mean_sd_path,
        predictions_path,
        preprocessing_path,
        config_path,
    ):
        print(f"  {path}")


# Global is used only for the reproducibility metadata saved above.
FEATURE_COLS_FOR_OUTPUT: list[str] = []


def main() -> None:
    global FEATURE_COLS_FOR_OUTPUT

    print("=" * 78)
    print("C-CASE ROBUSTNESS EXPERIMENT")
    print("=" * 78)
    print(f"Repository root : {ROOT_DIR}")
    print(f"Checkpoint      : {CHECKPOINT_PATH}")
    print(f"Output directory: {OUTPUT_DIR}")
    print(f"Seeds           : {ROBUSTNESS_SEEDS}")

    _, train_data, test_data, feature_cols = load_checkpoint()
    FEATURE_COLS_FOR_OUTPUT = feature_cols

    print("\nCheckpoint loaded successfully.")
    print(f"Development rows: {len(train_data):,}")
    print(f"Test rows       : {len(test_data):,}")
    print(f"Feature count   : {len(feature_cols)}")

    data = prepare_data(
        train_data,
        test_data,
        feature_cols,
    )

    print("\nPreprocessing verification:")
    print(f"  X_dev_scaled : {data['X_dev_scaled'].shape}")
    print(f"  X_test_scaled: {data['X_test_scaled'].shape}")
    print(f"  cluster_dev  : {data['cluster_dev_oh'].shape}")
    print(f"  cluster_test : {data['cluster_test_oh'].shape}")

    all_results = []
    all_predictions: dict[str, np.ndarray] = {}

    for seed in ROBUSTNESS_SEEDS:
        run_df, predictions = run_one_seed(seed, data)
        all_results.append(run_df)
        all_predictions.update(predictions)

    robustness_results = pd.concat(
        all_results,
        ignore_index=True,
    )

    expected_rows = len(ROBUSTNESS_SEEDS) * 5
    if len(robustness_results) != expected_rows:
        raise RuntimeError(
            f"Expected {expected_rows} result rows but found "
            f"{len(robustness_results)}."
        )

    mean_sd = create_mean_sd_table(robustness_results)

    save_outputs(
        robustness_results,
        mean_sd,
        all_predictions,
        data,
    )

    print("\n" + "=" * 78)
    print("ROBUSTNESS EXPERIMENT COMPLETED")
    print("=" * 78)

    print("\nAll-run results:")
    print(
        robustness_results[
            ["Seed", "Model", "CPU R2", "Memory R2"]
        ].to_string(
            index=False,
            float_format=lambda value: f"{value:.6f}",
        )
    )

    print("\nMean ± SD summary:")
    display_columns = [
        "Model",
        "CPU R2 Mean",
        "CPU R2 SD",
        "Memory R2 Mean",
        "Memory R2 SD",
    ]
    print(
        mean_sd[display_columns].to_string(
            index=False,
            float_format=lambda value: f"{value:.6f}",
        )
    )


if __name__ == "__main__":
    main()
